env:
  global:
    - secure: pJW/r7h3r45pelA24GP34NjDFURoBriteNg6gXOQY2SVIWbwrXl/lwtgT7o04OUXO049ZsXxmmYyrvGkkIcEPCKh8ishE+nl1FOhrSmMjfNm3DAGtAgX3PP6EZco1QIYk86GbeOiN8oV7rm78Snz7g5VnVuSDXkCJqEFueitvaA=
before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - cd ..
  - time wget -q http://www.libsdl.org/release/SDL2-2.0.3.tar.gz
  - time wget -q http://hivelocity.dl.sourceforge.net/project/sdl2gfx/SDL2_gfx-1.0.0.tar.gz
  - time tar xf SDL2-*.tar.gz
  - time tar xf SDL2_gfx-*.tar.gz
  - cd SDL2-*
  - ./configure && make && sudo make install
  - cd -
  - cd SDL2_gfx-*
  - ./configure && make && sudo make install
  - cd -
  - git clone https://github.com/AngryLawyer/rust-sdl2.git
  - rustc rust-sdl2/src/sdl2/lib.rs
script:
  - rustc -L. rust-sdl2_gfx/src/sdl2_gfx/lib.rs
  - rustdoc -L. rust-sdl2_gfx/src/sdl2_gfx/lib.rs
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
