language: rust
os:
    - linux
    - osx
addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-gfx-dev
env:
  global:
    - secure: pJW/r7h3r45pelA24GP34NjDFURoBriteNg6gXOQY2SVIWbwrXl/lwtgT7o04OUXO049ZsXxmmYyrvGkkIcEPCKh8ishE+nl1FOhrSmMjfNm3DAGtAgX3PP6EZco1QIYk86GbeOiN8oV7rm78Snz7g5VnVuSDXkCJqEFueitvaA=
    - LD_LIBRARY_PATH: /usr/local/lib
script:
  - cargo build -v
  - cargo test -v
  - cargo doc -v
after_script:
  - cp -R target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
  - rm -r doc
