[package]
name = "sdl2_image"
version = "0.0.2"
authors = ["xsleonard"]
description = "SDL2_image bindings and wrappers"
license = "MIT"

[lib]
name = "sdl2_image"
path = "src/sdl2_image/lib.rs"

[dependencies]
bitflags = "0.1"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2/"

[dependencies.sdl2-sys]
git = "https://github.com/AngryLawyer/rust-sdl2/"

[[bin]]
name = "demo"
path = "src/demo/main.rs"
