[package]

name = "rust-sdl2_mixer"
version = "0.0.1"
readme = "README.md"
authors = ["ShuYu Wang"]

[[lib]]

name = "sdl2_mixer"
path = "src/sdl2_mixer/lib.rs"

[dependencies.sdl2]

git = "https://github.com/AngryLawyer/rust-sdl2"

