[package]

name    = "sdl2"
version = "0.0.1"
authors = [ "Tony Aldridge<zaragopha@hotmail.com>" ]
build   = "sh prebuild.sh"

[lib]

name       = "sdl2"
path       = "src/sdl2/lib.rs"

[[bin]]

name = "demo"
path = "src/demo/main.rs"

