[package]
name = "sdl2_gfx"
version = "0.1.0"
authors = ["ShuYu Wang <andelf@gmail.com>"]

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"

[[lib]]
name = "sdl2_gfx"
path = "src/sdl2_gfx/lib.rs"
