[package]

name = "sdl2_mixer"
version = "0.0.1"
authors = ["ShuYu Wang<andelf@gmail.com>"]

[lib]

name = "sdl2_mixer"
path = "src/sdl2_mixer/lib.rs"

[[bin]]

name = "demo"
path = "src/demo/main.rs"

[dependencies.sdl2]

git = "https://github.com/AngryLawyer/rust-sdl2"
