[package]

name = "sdl2-sys"
description = "Raw SDL2 bindings for Rust, used internally rust-sdl2"
repository = "https://github.com/AngryLawyer/rust-sdl2"
version = "0.30.0"
authors = ["Tony Aldridge <tony@angry-lawyer.com>"]
keywords = ["SDL", "windowing", "graphics", "ffi"]
categories = ["rendering","games","external-ffi-bindings","game-engines","multimedia"]
license = "MIT"
links = "SDL2"
build = "build.rs"

[lib]
name = "sdl2_sys"
path = "src/lib.rs"

[build-dependencies.bindgen]
version = "0.30"
optional = true

[build-dependencies.pkg-config]
version = "0.3.9"
optional = true

[features]

default = []
use-pkgconfig = ["pkg-config"]
use-bindgen = ["bindgen"]
use_mac_framework = []
