[package]

name = "sdl2-sys"
version = "0.0.0"
authors = ["Tony Aldridge <tony@angry-lawyer.com>"]
links = "SDL2"
build = "build.rs"

[lib]
name = "sdl2-sys"
path = "src/lib.rs"

[build-dependencies]
pkg-config = "*"

[features]

default = []
use-pkgconfig = []
