[package]

name = "sdl2-sys"
description = "Raw SDL2 bindings for Rust, used internally rust-sdl2"
repository = "https://github.com/AngryLawyer/rust-sdl2"
version = "0.6.0"
authors = ["Tony Aldridge <tony@angry-lawyer.com>"]
license = "MIT"
links = "SDL2"
build = "build.rs"

[lib]
name = "sdl2_sys"
path = "src/lib.rs"

[dependencies]
num = "0.1"
libc = "0.1"

[build-dependencies.pkg-config]
version = "0.3"
optional = true

[features]

default = []
use-pkgconfig = ["pkg-config"]
no_std = []
